### ISSUE TITLE
Looks like Live Demo is broken

### ISSUE THREAD

**Issue by EsteveSegura** [Millennium-Fennec/ThreeOrbitControlsGizmo#3]
https://fennec-hub.github.io/ThreeOrbitControlsGizmo/

The issue is in:
https://threejs.org/examples/jsm/libs/dat.gui.module.js  -- 404 Error

![image](https://user-images.githubusercontent.com/10067827/191627769-ce996629-31ad-4d85-af9a-1dbaecc74174.png)

**Comment by Fennec-hub** [comment]
Fixed, It was a `cdn` problem.

Thanks for the heads-up
