### ISSUE TITLE
How to use camera-controls correctly instead of default controls?

### ISSUE THREAD

**Issue by WREQI** [Millennium-Fennec/ThreeOrbitControlsGizmo#6]
How to use camera-controls correctly instead of default controls?
https://github.com/yomotsu/camera-controls
https://codesandbox.io/p/sandbox/xenodochial-aryabhata-pcdb5v?file=%2Fsrc%2Findex.js%3A16%2C1

**Comment by Fennec-hub** [comment]
Please don't use this library, it has been deprecated.

To answer your initial question, I suggest to use this veiwport helper [source](https://github.com/Fennec-hub/viewHelper) - [codesandbox](https://codesandbox.io/s/xenodochial-aryabhata-pcdb5v?file=%2Fsrc%2FViewHelper.js). inspired from the official [viewport helper](https://discourse.threejs.org/t/interactive-viewhelper/46246/3), but <ins> independent from any controller</ins>.

**Comment by WREQI** [comment]
https://codesandbox.io/s/xenodochial-aryabhata-pcdb5v?file=%2Fsrc%2FViewHelper.js   

That's what I'm using, but I don't know how to combine it with it    https://github.com/yomotsu/camera-controls @Fennec-hub

**Comment by Fennec-hub** [comment]
https://github.com/yomotsu/camera-controls, has an [`update`](https://github.com/yomotsu/camera-controls?tab=readme-ov-file#events) event, use it like so:
 
 ````
 // don't use gizmo.setControls
 cameraControl.addEventListener( 'update', (e) => {
     //...
     gizmo.update();
     //...
 })
 ````

**Comment by WREQI** [comment]
![image](https://github.com/Fennec-hub/ThreeOrbitControlsGizmo/assets/35467304/8b07806e-c065-4f7f-b11e-e08127ec4225)
Can you write a simple example? When I click x,y,z in the gizmo, the controller camera doesn't rotate @Fennec-hub

**Comment by Fennec-hub** [comment]
Sorry I'm a bit busy right now. Give me a couple days, I'm gonna refactor it with a new repo, an npm installer, and new examples ... I'll notify you when it's done.

**Comment by WREQI** [comment]
> 对不起，我现在有点忙。给我几天时间，我将使用新的存储库、npm 安装程序和新示例重构它......完成后我会通知你。

我已经解决了，谢谢

**Comment by WREQI** [comment]
@Fennec-hub I've solved it, thanks
